# Generated by Django 5.1.7 on 2025-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0061_rename_text_about_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="gif",
            field=models.FileField(
                blank=True,
                help_text="Upload a GIF file here. This will be displayed instead of the image if provided.",
                null=True,
                upload_to="static/assets/banner",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/assets/banner"
            ),
        ),
    ]
