# Generated by Django 5.1.7 on 2025-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0062_banner_gif_alter_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="features",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/assets/features/icons"
            ),
        ),
    ]
