# Generated by Django 5.1.7 on 2025-05-18 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0063_features_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="features",
            name="icon",
        ),
    ]
