# Generated by Django 5.1.7 on 2025-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0065_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Ticker Content")),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Show this ticker on the site?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Application",
        ),
    ]
