# Generated by Django 5.1.7 on 2025-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0066_newsticker_delete_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="keywords",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Highlight Keywords (comma-separated)",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="about",
            field=models.TextField(verbose_name="About Us Text"),
        ),
    ]
