# Generated by Django 5.1.7 on 2025-05-26 04:47

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0067_about_keywords_alter_about_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about",
            field=django_summernote.fields.SummernoteTextField(
                verbose_name="About Us Text"
            ),
        ),
    ]
