# Generated by Django 5.1.7 on 2025-05-26 05:14

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0068_alter_about_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_summernote.fields.SummernoteTextField(
                        verbose_name="About Us Text"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Highlight Keywords (comma-separated)",
                    ),
                ),
            ],
        ),
    ]
