# Generated by Django 5.1.7 on 2025-04-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atimeslot',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
