# Generated by Django 5.1.7 on 2025-04-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_floor_remove_atimeslot_email_booking_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='floor_id_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='floor',
        ),
        migrations.AddField(
            model_name='booking',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.floor'),
        ),
    ]
