# Generated by Django 5.1.7 on 2025-04-24 18:01

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_fix_booking_floor_relationship'),
    ]

    operations = [
        # Fix any potential NULL values in floor_id column
        migrations.RunSQL(
            """
            UPDATE booking_booking 
            SET floor_id = (SELECT id FROM booking_floor ORDER BY id LIMIT 1) 
            WHERE floor_id IS NULL;
            """,
            reverse_sql="""
            -- No reverse operation needed
            """
        ),
        # Ensure the floor_id column has the correct constraints
        migrations.RunSQL(
            """
            ALTER TABLE booking_booking ALTER COLUMN floor_id SET NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE booking_booking ALTER COLUMN floor_id DROP NOT NULL;
            """
        ),
        # Add proper foreign key constraint if missing
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'booking_booking_floor_id_fkey' AND conrelid = 'booking_booking'::regclass
                ) THEN
                    ALTER TABLE booking_booking 
                    ADD CONSTRAINT booking_booking_floor_id_fkey 
                    FOREIGN KEY (floor_id) REFERENCES booking_floor(id) ON DELETE CASCADE;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            -- No reverse operation needed
            """
        )
    ]
