# Generated by Django 5.1.7 on 2025-05-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_alter_floor_booking_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("Instant Booking", "Instant Booking"),
                    ("Requires Approval", "Requires Approval"),
                ],
                default="Instant Booking",
                max_length=50,
            ),
        ),
    ]
