# Generated by Django 5.1.7 on 2025-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_floor_number_of_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atimeslot",
            name="room",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
