# Generated by Django 5.1.7 on 2025-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_atimeslot_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="atimeslot",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
