# Generated by Django 5.1.7 on 2025-04-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20250424_2246'),
    ]

    operations = [
        # First, ensure all existing data is preserved in floor_id_temp
        migrations.RunSQL(
            """
            UPDATE booking_booking 
            SET floor_id_temp = floor_id 
            WHERE floor_id IS NOT NULL AND floor_id_temp IS NULL;
            """,
            reverse_sql="""
            UPDATE booking_booking 
            SET floor_id = floor_id_temp 
            WHERE floor_id_temp IS NOT NULL AND floor_id IS NULL;
            """
        ),
        # Now properly set up the floor foreign key using the preserved IDs
        migrations.RunSQL(
            """
            UPDATE booking_booking 
            SET floor_id = floor_id_temp 
            WHERE floor_id_temp IS NOT NULL;
            """,
            reverse_sql="""
            UPDATE booking_booking 
            SET floor_id_temp = floor_id 
            WHERE floor_id IS NOT NULL;
            """
        ),
        # Make floor field required again
        migrations.AlterField(
            model_name='booking',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.floor'),
        ),
        # Remove the temporary field once migration is complete
        migrations.RemoveField(
            model_name='booking',
            name='floor_id_temp',
        ),
    ]