# Generated by Django 5.1.7 on 2025-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_fix_booking_floor_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("Instant Booking", "Instant Booking"),
                    ("requires approval", "Requires Approval"),
                ],
                default="instant",
                max_length=50,
            ),
        ),
    ]
