# Generated by Django 5.1.7 on 2025-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_floor_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="number_of_rooms",
            field=models.IntegerField(default=5),
        ),
    ]
