# Generated by Django 5.1.7 on 2025-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_floor_number_of_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="atimeslot",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
