# Generated by Django 5.1.7 on 2025-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_atimeslot_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atimeslot",
            name="room",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
