# Generated by Django 5.1.7 on 2025-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickethistory",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
