# Generated by Django 5.1.7 on 2025-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_tickethistory_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="updated_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
